//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập đủ họ tên")]
        [StringLength(100, ErrorMessage = "Tên tối đa là 100 ký tự, tối thiểu là 1 ký tự", MinimumLength = 1)]//Tên đăng nhập tối thiểu là 5 ký tự, tối đa là 50
        [RegularExpression(@"\w*", ErrorMessage = "Vui lòng chỉ nhập các ký từ thường và in hoa(a-z) và số")]//Bắt buộc nhập chữ(không nhập số và các kí tự đặt biệt), tự viết lại dòng báo lỗi theo ý minhf
        [Display(Name = "Tên admin")]
        public string NameUser { get; set; }
        [Required(ErrorMessage = "Tên đăng nhập không được để trống")]
        [StringLength(10, ErrorMessage = "Tên đăng nhập tối thiểu là 5 ký tự, tối đa là 10", MinimumLength = 5)]//Tên đăng nhập tối thiểu là 5 ký tự, tối đa là 50
        [RegularExpression(@"\w*", ErrorMessage = "Vui lòng chỉ nhập các ký từ thường và in hoa(a-z) và số")]//Bắt buộc nhập chữ(không nhập số và các kí tự đặt biệt), tự viết lại dòng báo lỗi theo ý minhf
        [Display(Name = "Tên đăng nhập")]
        public string AccountUser { get; set; }

        [DisplayName("Nhập mật khẩu")]
        [Required(ErrorMessage = "Pass không được để trống")]//Yêu cầu phải nhập Pass
        [RegularExpression(@"\w*", ErrorMessage = "Vui lòng chỉ nhập các ký từ thường và in hoa(a-z) và số")]
        [DataType(DataType.Password)]
        public string PasswordUser { get; set; }

        [NotMapped]
        [Compare("PasswordUser", ErrorMessage = "Mật khẩu nhập lại không chính xác")]
        [DisplayName("Nhập lại mật khẩu")]

        public string ConfirmPass { get; set; }
        [NotMapped]

        public string ErrorLogin { get; set; }
    }
}
